# Generated by Django 4.2.11 on 2024-05-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposProductos',
            new_name='Categoria',
        ),
    ]
