# Generated by Django 4.2.11 on 2024-05-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tiposproductos_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
